ros__parameters:
  update_rate: 100

  joint_state_broadcaster:
    type: joint_state_broadcaster/JointStateBroadcaster

  rotary_table_controller:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - rotary_table_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 100.0
    action_monitor_rate: 10.0
